# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='cart.CartItem'),
        ),
    ]
